name: sample_remote_data
version: 1.0.1
description: A sample Dart package for fetching remote data.
author: Uday Hiwarale <thatisuday@gmail.com>
homepage: https://github.com/thatisuday/sample_remote_data
repository: https://github.com/thatisuday/sample_remote_data.git
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  http: ^0.12.0+2